import codecs
import json
import re

FOODS = [
    # 1. Fresh Juices & Beverages
    {"id": "fresh_lime_soda_sweet", "name": "Fresh Lime Soda (Sweet)", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 44, "protein": 0.1, "carbs": 11.2, "fat": 0, "fiber": 0}, "image": None},
    {"id": "fresh_lime_soda_salt", "name": "Fresh Lime Soda (Salt)", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 10, "protein": 0.1, "carbs": 2.5, "fat": 0, "fiber": 0}, "image": None},
    {"id": "lemon_masala_soda", "name": "Lemon Masala Soda", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 25, "protein": 0.2, "carbs": 6, "fat": 0, "fiber": 0}, "image": None},
    {"id": "nannari_sarbath", "name": "Nannari Sarbath", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 52, "protein": 0.1, "carbs": 13, "fat": 0, "fiber": 0}, "image": None},
    {"id": "fresh_lemon_juice", "name": "Fresh Lemon Juice (Sweetened)", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 40, "protein": 0.2, "carbs": 10, "fat": 0, "fiber": 0}, "image": None},
    {"id": "fresh_watermelon_juice", "name": "Fresh Watermelon Juice", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 30, "protein": 0.6, "carbs": 7.6, "fat": 0.2, "fiber": 0.4}, "image": None},
    {"id": "fresh_orange_juice", "name": "Fresh Orange Juice", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 45, "protein": 0.7, "carbs": 10.4, "fat": 0.2, "fiber": 0.2}, "image": None},
    {"id": "pomegranate_juice", "name": "Fresh Pomegranate Juice", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 54, "protein": 0.2, "carbs": 13.1, "fat": 0.3, "fiber": 0.1}, "image": None},
    {"id": "apple_juice_fresh", "name": "Fresh Apple Juice", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 46, "protein": 0.1, "carbs": 11.3, "fat": 0.1, "fiber": 0.2}, "image": None},
    {"id": "grape_juice_fresh", "name": "Fresh Grape Juice", "category": "beverages", "subcategory": "Fresh Juices", "servingType": "volume", "defaultServing": {"unit": "glass", "amount": 1}, "servingOptions": [{"label": "Regular Glass (250ml)", "grams": 250}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 60, "protein": 0.4, "carbs": 14.8, "fat": 0.1, "fiber": 0.2}, "image": None},

    # 2. Cakes & Chocolates
    {"id": "cake_dutch_truffle", "name": "Dutch Truffle Cake", "category": "snacks", "subcategory": "Cakes", "servingType": "grams", "defaultServing": {"unit": "slice", "amount": 1}, "servingOptions": [{"label": "1 Slice (100g)", "grams": 100}, {"label": "Half Kg Cake", "grams": 500}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 410, "protein": 5, "carbs": 52, "fat": 22, "fiber": 2.5}, "image": None},
    {"id": "cake_chocolate_mousse", "name": "Chocolate Mousse Cake", "category": "snacks", "subcategory": "Cakes", "servingType": "grams", "defaultServing": {"unit": "slice", "amount": 1}, "servingOptions": [{"label": "1 Slice (100g)", "grams": 100}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 380, "protein": 4.5, "carbs": 44, "fat": 21, "fiber": 2}, "image": None},
    {"id": "cake_red_velvet", "name": "Red Velvet Cake", "category": "snacks", "subcategory": "Cakes", "servingType": "grams", "defaultServing": {"unit": "slice", "amount": 1}, "servingOptions": [{"label": "1 Slice (100g)", "grams": 100}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 390, "protein": 4.8, "carbs": 55, "fat": 18, "fiber": 0.8}, "image": None},
    {"id": "cake_black_forest", "name": "Black Forest Cake", "category": "snacks", "subcategory": "Cakes", "servingType": "grams", "defaultServing": {"unit": "slice", "amount": 1}, "servingOptions": [{"label": "1 Slice (100g)", "grams": 100}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 330, "protein": 4, "carbs": 48, "fat": 14, "fiber": 1}, "image": None},
    {"id": "cake_ny_cheesecake", "name": "New York Baked Cheesecake", "category": "snacks", "subcategory": "Cakes", "servingType": "grams", "defaultServing": {"unit": "slice", "amount": 1}, "servingOptions": [{"label": "1 Slice (120g)", "grams": 120}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 321, "protein": 6.1, "carbs": 25.5, "fat": 22.5, "fiber": 0.4}, "image": None},
    {"id": "chocolate_brownie", "name": "Chocolate Brownie", "category": "snacks", "subcategory": "Cakes", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Piece (80g)", "grams": 80}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 466, "protein": 5.4, "carbs": 54, "fat": 27, "fiber": 3}, "image": None},
    
    {"id": "choc_dairy_milk", "name": "Cadbury Dairy Milk", "category": "snacks", "subcategory": "Chocolates", "servingType": "count", "defaultServing": {"unit": "bar", "amount": 1}, "servingOptions": [{"label": "1 Small Bar (13g)", "grams": 13}, {"label": "1 Regular Bar (50g)", "grams": 50}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 530, "protein": 7.3, "carbs": 60.5, "fat": 29.5, "fiber": 0.6}, "image": None},
    {"id": "choc_bournville", "name": "Cadbury Bournville (Dark)", "category": "snacks", "subcategory": "Chocolates", "servingType": "count", "defaultServing": {"unit": "bar", "amount": 1}, "servingOptions": [{"label": "1 Bar (80g)", "grams": 80}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 526, "protein": 5.2, "carbs": 61, "fat": 30, "fiber": 7.2}, "image": None},
    {"id": "choc_5_star", "name": "Cadbury 5 Star", "category": "snacks", "subcategory": "Chocolates", "servingType": "count", "defaultServing": {"unit": "bar", "amount": 1}, "servingOptions": [{"label": "1 Bar (20g)", "grams": 20}, {"label": "1 Large Bar (40g)", "grams": 40}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 451, "protein": 3.2, "carbs": 70, "fat": 17.5, "fiber": 0}, "image": None},
    {"id": "choc_kitkat", "name": "Nestle KitKat", "category": "snacks", "subcategory": "Chocolates", "servingType": "count", "defaultServing": {"unit": "pack", "amount": 1}, "servingOptions": [{"label": "2 Fingers (18g)", "grams": 18}, {"label": "4 Fingers (36g)", "grams": 36}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 502, "protein": 6.8, "carbs": 64.6, "fat": 24, "fiber": 1.6}, "image": None},
    {"id": "choc_snickers", "name": "Snickers", "category": "snacks", "subcategory": "Chocolates", "servingType": "count", "defaultServing": {"unit": "bar", "amount": 1}, "servingOptions": [{"label": "1 Bar (45g)", "grams": 45}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 488, "protein": 8.6, "carbs": 60.5, "fat": 23.5, "fiber": 1.5}, "image": None},
    {"id": "choc_ferrero_rocher", "name": "Ferrero Rocher", "category": "snacks", "subcategory": "Chocolates", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Piece (12.5g)", "grams": 12.5}, {"label": "3 Pieces (37.5g)", "grams": 37.5}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 603, "protein": 8.2, "carbs": 44.4, "fat": 42.7, "fiber": 4.1}, "image": None},
    {"id": "choc_amul_dark", "name": "Amul Dark Chocolate (99% / 75%)", "category": "snacks", "subcategory": "Chocolates", "servingType": "count", "defaultServing": {"unit": "bar", "amount": 1}, "servingOptions": [{"label": "2 Squares (15g)", "grams": 15}, {"label": "1 Bar (150g)", "grams": 150}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 587, "protein": 10, "carbs": 33, "fat": 50, "fiber": 14}, "image": None},

    # 3. Dals & Pulses
    {"id": "moong_dal_sprouts", "name": "Moong Dal Sprouts (Raw)", "category": "curries", "subcategory": "Dals & Pulses", "servingType": "grams", "defaultServing": {"unit": "cup", "amount": 1}, "servingOptions": [{"label": "1 Cup (100g)", "grams": 100}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 30, "protein": 3.0, "carbs": 5.9, "fat": 0.2, "fiber": 1.8}, "image": None},
    {"id": "rajma_curry", "name": "Rajma Curry (Kidney Beans)", "category": "curries", "subcategory": "Dals & Pulses", "servingType": "grams", "defaultServing": {"unit": "bowl", "amount": 1}, "servingOptions": [{"label": "1 Bowl (200g)", "grams": 200}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 110, "protein": 5.5, "carbs": 15, "fat": 3.5, "fiber": 4.5}, "image": None},
    {"id": "chana_masala", "name": "Chana Masala (Chole)", "category": "curries", "subcategory": "Dals & Pulses", "servingType": "grams", "defaultServing": {"unit": "bowl", "amount": 1}, "servingOptions": [{"label": "1 Bowl (200g)", "grams": 200}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 145, "protein": 6, "carbs": 18, "fat": 6, "fiber": 5}, "image": None},
    {"id": "toor_dal_yellow", "name": "Yellow Toor Dal (Cooked)", "category": "curries", "subcategory": "Dals & Pulses", "servingType": "grams", "defaultServing": {"unit": "bowl", "amount": 1}, "servingOptions": [{"label": "1 Bowl (200g)", "grams": 200}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 105, "protein": 5, "carbs": 16, "fat": 2, "fiber": 4}, "image": None},
    {"id": "masoor_dal_red", "name": "Red Masoor Dal (Cooked)", "category": "curries", "subcategory": "Dals & Pulses", "servingType": "grams", "defaultServing": {"unit": "bowl", "amount": 1}, "servingOptions": [{"label": "1 Bowl (200g)", "grams": 200}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 116, "protein": 9, "carbs": 20, "fat": 0.4, "fiber": 8}, "image": None},
    {"id": "urad_dal_black", "name": "Black Urad Dal / Dal Makhani (Cooked)", "category": "curries", "subcategory": "Dals & Pulses", "servingType": "grams", "defaultServing": {"unit": "bowl", "amount": 1}, "servingOptions": [{"label": "1 Bowl (200g)", "grams": 200}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 130, "protein": 4.5, "carbs": 12, "fat": 7.5, "fiber": 3.5}, "image": None},
    {"id": "lobia_curry", "name": "Lobia Curry (Black Eyed Peas)", "category": "curries", "subcategory": "Dals & Pulses", "servingType": "grams", "defaultServing": {"unit": "bowl", "amount": 1}, "servingOptions": [{"label": "1 Bowl (200g)", "grams": 200}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 105, "protein": 4, "carbs": 15, "fat": 3, "fiber": 3.8}, "image": None},

    # 4. Indian Sweets
    {"id": "sweet_mysore_pak", "name": "Mysore Pak (Ghee)", "category": "snacks", "subcategory": "Sweets", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Piece (40g)", "grams": 40}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 526, "protein": 4.2, "carbs": 58, "fat": 31, "fiber": 0.8}, "image": None},
    {"id": "sweet_boondi_laddu", "name": "Boondhi Laddu", "category": "snacks", "subcategory": "Sweets", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Piece (45g)", "grams": 45}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 480, "protein": 8, "carbs": 62, "fat": 23, "fiber": 1}, "image": None},
    {"id": "sweet_badam_halwa", "name": "Badam Halwa", "category": "snacks", "subcategory": "Sweets", "servingType": "grams", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Portion (50g)", "grams": 50}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 510, "protein": 8.5, "carbs": 44, "fat": 34, "fiber": 4}, "image": None},
    {"id": "sweet_wheat_halwa", "name": "Wheat Halwa (Tirunelveli Halwa)", "category": "snacks", "subcategory": "Sweets", "servingType": "grams", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Portion (50g)", "grams": 50}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 420, "protein": 3.5, "carbs": 55, "fat": 20, "fiber": 1.2}, "image": None},
    {"id": "sweet_badusha", "name": "Badusha / Balushahi", "category": "snacks", "subcategory": "Sweets", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Piece (50g)", "grams": 50}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 456, "protein": 4.1, "carbs": 51, "fat": 26, "fiber": 0.5}, "image": None},
    {"id": "sweet_chandrakala", "name": "Chandrakala", "category": "snacks", "subcategory": "Sweets", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Piece (60g)", "grams": 60}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 410, "protein": 5, "carbs": 54, "fat": 19, "fiber": 1}, "image": None},
    {"id": "sweet_basundi", "name": "Basundi", "category": "snacks", "subcategory": "Sweets", "servingType": "volume", "defaultServing": {"unit": "bowl", "amount": 1}, "servingOptions": [{"label": "1 Bowl (150ml)", "grams": 150}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 210, "protein": 6, "carbs": 24, "fat": 10, "fiber": 0}, "image": None},
    {"id": "sweet_angoor_jamun", "name": "Angoor Jamun", "category": "snacks", "subcategory": "Sweets", "servingType": "count", "defaultServing": {"unit": "pieces", "amount": 3}, "servingOptions": [{"label": "3 Pieces (45g)", "grams": 45}, {"label": "5 Pieces (75g)", "grams": 75}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 300, "protein": 6, "carbs": 48, "fat": 9, "fiber": 0}, "image": None},
    {"id": "sweet_gulab_jamun", "name": "Gulab Jamun", "category": "snacks", "subcategory": "Sweets", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "2 Pieces (80g)", "grams": 80}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 320, "protein": 5, "carbs": 54, "fat": 10, "fiber": 0}, "image": None},
    {"id": "sweet_kaju_katli", "name": "Kaju Katli", "category": "snacks", "subcategory": "Sweets", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Piece (15g)", "grams": 15}, {"label": "2 Pieces (30g)", "grams": 30}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 480, "protein": 9, "carbs": 56, "fat": 25, "fiber": 2}, "image": None},
    {"id": "sweet_jalebi", "name": "Jalebi", "category": "snacks", "subcategory": "Sweets", "servingType": "grams", "defaultServing": {"unit": "pieces", "amount": 2}, "servingOptions": [{"label": "2 Pieces (50g)", "grams": 50}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 385, "protein": 2.5, "carbs": 76, "fat": 8, "fiber": 0.5}, "image": None},
    {"id": "sweet_doodh_peda", "name": "Doodh Peda", "category": "snacks", "subcategory": "Sweets", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Piece (20g)", "grams": 20}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 380, "protein": 9.5, "carbs": 62, "fat": 10, "fiber": 0}, "image": None},
    {"id": "sweet_kesar_peda", "name": "Kesar Peda", "category": "snacks", "subcategory": "Sweets", "servingType": "count", "defaultServing": {"unit": "piece", "amount": 1}, "servingOptions": [{"label": "1 Piece (25g)", "grams": 25}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 385, "protein": 9.2, "carbs": 61, "fat": 11, "fiber": 0}, "image": None},

    # 5. Biscuits & Wafers
    {"id": "biscuit_hide_n_seek", "name": "Parle Hide & Seek", "category": "snacks", "subcategory": "Biscuits", "servingType": "count", "defaultServing": {"unit": "biscuits", "amount": 2}, "servingOptions": [{"label": "2 Biscuits (16g)", "grams": 16}, {"label": "5 Biscuits (40g)", "grams": 40}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 483, "protein": 5.4, "carbs": 73, "fat": 18.8, "fiber": 3}, "image": None},
    {"id": "biscuit_bourbon", "name": "Britannia Bourbon", "category": "snacks", "subcategory": "Biscuits", "servingType": "count", "defaultServing": {"unit": "biscuits", "amount": 2}, "servingOptions": [{"label": "2 Biscuits (25g)", "grams": 25}, {"label": "4 Biscuits (50g)", "grams": 50}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 486, "protein": 5, "carbs": 69.5, "fat": 21, "fiber": 1}, "image": None},
    {"id": "biscuit_dark_fantasy", "name": "Dark Fantasy Choco Fills", "category": "snacks", "subcategory": "Biscuits", "servingType": "count", "defaultServing": {"unit": "cookie", "amount": 1}, "servingOptions": [{"label": "1 Cookie (12.5g)", "grams": 12.5}, {"label": "2 Cookies (25g)", "grams": 25}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 512, "protein": 5.1, "carbs": 64.9, "fat": 25.8, "fiber": 2.5}, "image": None},
    {"id": "biscuit_milk_bikis", "name": "Britannia Milk Bikis", "category": "snacks", "subcategory": "Biscuits", "servingType": "count", "defaultServing": {"unit": "biscuits", "amount": 2}, "servingOptions": [{"label": "4 Biscuits (25g)", "grams": 25}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 454, "protein": 7.5, "carbs": 74, "fat": 14.5, "fiber": 1.2}, "image": None},
    {"id": "biscuit_oreo", "name": "Oreo Cookies", "category": "snacks", "subcategory": "Biscuits", "servingType": "count", "defaultServing": {"unit": "cookies", "amount": 3}, "servingOptions": [{"label": "3 Cookies (34g)", "grams": 34}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 480, "protein": 5, "carbs": 70, "fat": 20, "fiber": 3}, "image": None},
    {"id": "biscuit_monaco", "name": "Parle Monaco", "category": "snacks", "subcategory": "Biscuits", "servingType": "count", "defaultServing": {"unit": "biscuits", "amount": 5}, "servingOptions": [{"label": "5 Biscuits (17.5g)", "grams": 17.5}, {"label": "10 Biscuits (35g)", "grams": 35}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 501, "protein": 7, "carbs": 68, "fat": 22.5, "fiber": 2}, "image": None},
    {"id": "biscuit_50_50", "name": "Britannia 50/50 Sweet & Salty", "category": "snacks", "subcategory": "Biscuits", "servingType": "count", "defaultServing": {"unit": "biscuits", "amount": 5}, "servingOptions": [{"label": "5 Biscuits (18g)", "grams": 18}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 488, "protein": 7.4, "carbs": 68.3, "fat": 20.6, "fiber": 2.2}, "image": None},
    
    {"id": "wafer_vanilla", "name": "Vanilla Cream Wafers", "category": "snacks", "subcategory": "Biscuits", "servingType": "grams", "defaultServing": {"unit": "pack", "amount": 1}, "servingOptions": [{"label": "Small Pack (45g)", "grams": 45}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 500, "protein": 3.5, "carbs": 68, "fat": 24, "fiber": 0.5}, "image": None},
    {"id": "wafer_chocolate", "name": "Chocolate Cream Wafers", "category": "snacks", "subcategory": "Biscuits", "servingType": "grams", "defaultServing": {"unit": "pack", "amount": 1}, "servingOptions": [{"label": "Small Pack (45g)", "grams": 45}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 510, "protein": 4.5, "carbs": 67, "fat": 25, "fiber": 2}, "image": None},
    {"id": "wafer_strawberry", "name": "Strawberry Cream Wafers", "category": "snacks", "subcategory": "Biscuits", "servingType": "grams", "defaultServing": {"unit": "pack", "amount": 1}, "servingOptions": [{"label": "Small Pack (45g)", "grams": 45}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 495, "protein": 3.2, "carbs": 69, "fat": 23.5, "fiber": 0.4}, "image": None},
    {"id": "wafer_orange", "name": "Orange Cream Wafers", "category": "snacks", "subcategory": "Biscuits", "servingType": "grams", "defaultServing": {"unit": "pack", "amount": 1}, "servingOptions": [{"label": "Small Pack (45g)", "grams": 45}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 490, "protein": 3.3, "carbs": 69, "fat": 23, "fiber": 0.5}, "image": None},
    {"id": "wafer_pineapple", "name": "Pineapple Cream Wafers", "category": "snacks", "subcategory": "Biscuits", "servingType": "grams", "defaultServing": {"unit": "pack", "amount": 1}, "servingOptions": [{"label": "Small Pack (45g)", "grams": 45}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 490, "protein": 3.2, "carbs": 69.5, "fat": 22.5, "fiber": 0.5}, "image": None},

    # 6. Cheeses
    {"id": "cheese_amul_processed", "name": "Amul Processed Cheese (Slice/Cube)", "category": "dairy", "subcategory": "Cheese", "servingType": "count", "defaultServing": {"unit": "slice/cube", "amount": 1}, "servingOptions": [{"label": "1 Slice/Cube (20g)", "grams": 20}, {"label": "2 Slices/Cubes (40g)", "grams": 40}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 314, "protein": 20, "carbs": 1.5, "fat": 26, "fiber": 0}, "image": None},
    {"id": "cheese_cheddar", "name": "Cheddar Cheese", "category": "dairy", "subcategory": "Cheese", "servingType": "grams", "defaultServing": {"unit": "slice", "amount": 1}, "servingOptions": [{"label": "1 Slice (28g)", "grams": 28}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 403, "protein": 24.9, "carbs": 1.3, "fat": 33.1, "fiber": 0}, "image": None},
    {"id": "cheese_mozzarella", "name": "Mozzarella Cheese (Pizza Cheese)", "category": "dairy", "subcategory": "Cheese", "servingType": "grams", "defaultServing": {"unit": "cup", "amount": 1}, "servingOptions": [{"label": "1/4 Cup Grated (28g)", "grams": 28}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 280, "protein": 28, "carbs": 3.1, "fat": 17.1, "fiber": 0}, "image": None},
    {"id": "cheese_parmesan", "name": "Parmesan Cheese (Grated)", "category": "dairy", "subcategory": "Cheese", "servingType": "grams", "defaultServing": {"unit": "tbsp", "amount": 1}, "servingOptions": [{"label": "1 Tbsp (5g)", "grams": 5}, {"label": "1/4 Cup (25g)", "grams": 25}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 431, "protein": 38.5, "carbs": 4.1, "fat": 29.2, "fiber": 0}, "image": None},
    {"id": "cheese_feta", "name": "Feta Cheese", "category": "dairy", "subcategory": "Cheese", "servingType": "grams", "defaultServing": {"unit": "crumble", "amount": 1}, "servingOptions": [{"label": "1/4 Cup Crumbled (38g)", "grams": 38}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 264, "protein": 14.2, "carbs": 4.1, "fat": 21.3, "fiber": 0}, "image": None},

    # 7. Wraps & Rolls
    {"id": "roll_classic_veg", "name": "Classic Veg Frankie / Roll", "category": "meals", "subcategory": "Wraps & Rolls", "servingType": "count", "defaultServing": {"unit": "roll", "amount": 1}, "servingOptions": [{"label": "1 Roll (200g)", "grams": 200}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 175, "protein": 4.5, "carbs": 26, "fat": 6, "fiber": 3.5}, "image": None},
    {"id": "roll_tawa_paneer", "name": "Tawa Paneer Frankie / Roll", "category": "meals", "subcategory": "Wraps & Rolls", "servingType": "count", "defaultServing": {"unit": "roll", "amount": 1}, "servingOptions": [{"label": "1 Roll (220g)", "grams": 220}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 220, "protein": 9.5, "carbs": 24, "fat": 10, "fiber": 2.5}, "image": None},
    {"id": "roll_schezwan_paneer", "name": "Schezwan Paneer Frankie / Roll", "category": "meals", "subcategory": "Wraps & Rolls", "servingType": "count", "defaultServing": {"unit": "roll", "amount": 1}, "servingOptions": [{"label": "1 Roll (220g)", "grams": 220}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 230, "protein": 9, "carbs": 25, "fat": 11, "fiber": 2.2}, "image": None},
    {"id": "roll_chicken_tikka", "name": "Chicken Tikka Frankie / Roll", "category": "meals", "subcategory": "Wraps & Rolls", "servingType": "count", "defaultServing": {"unit": "roll", "amount": 1}, "servingOptions": [{"label": "1 Roll (230g)", "grams": 230}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 210, "protein": 14, "carbs": 22, "fat": 7.5, "fiber": 2}, "image": None},
    {"id": "roll_classic_chicken", "name": "Classic Chicken Frankie / Roll", "category": "meals", "subcategory": "Wraps & Rolls", "servingType": "count", "defaultServing": {"unit": "roll", "amount": 1}, "servingOptions": [{"label": "1 Roll (220g)", "grams": 220}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 215, "protein": 13.5, "carbs": 23, "fat": 8, "fiber": 1.8}, "image": None},
    {"id": "roll_mutton_seekh", "name": "Mutton Seekh Frankie / Roll", "category": "meals", "subcategory": "Wraps & Rolls", "servingType": "count", "defaultServing": {"unit": "roll", "amount": 1}, "servingOptions": [{"label": "1 Roll (220g)", "grams": 220}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 240, "protein": 14, "carbs": 21, "fat": 11, "fiber": 1.5}, "image": None},
    {"id": "roll_egg", "name": "Classic Egg Roll", "category": "meals", "subcategory": "Wraps & Rolls", "servingType": "count", "defaultServing": {"unit": "roll", "amount": 1}, "servingOptions": [{"label": "1 Roll (200g)", "grams": 200}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 195, "protein": 8, "carbs": 24, "fat": 8, "fiber": 2}, "image": None},

    # 8. Vegetables
    {"id": "tomato_onion_stir_fry", "name": "Tomato Onion Stir Fry", "category": "vegetables", "subcategory": "Dry Sabzi", "servingType": "volume", "defaultServing": {"unit": "katori", "amount": 1}, "servingOptions": [{"label": "Small Katori (100g)", "grams": 100}, {"label": "Regular Bowl (180g)", "grams": 180}, { "label": "Custom (g)", "grams": None }], "per100g": {"calories": 65, "protein": 1.2, "carbs": 7.5, "fat": 3.5, "fiber": 1.8}, "image": None},
]

# Generate Foods JS string
foods_str = ""
for item in FOODS:
    foods_str += "    { \"id\": \"" + item["id"] + "\", \"name\": \"" + item["name"] + "\", \"category\": \"" + item["category"] + "\", \"subcategory\": \"" + item["subcategory"] + "\", \"servingType\": \"" + item["servingType"] + "\", \"defaultServing\": { \"unit\": \"" + item["defaultServing"]["unit"] + "\", \"amount\": " + str(item["defaultServing"]["amount"]) + " }, \"servingOptions\": " + json.dumps(item["servingOptions"]) + ", \"per100g\": " + json.dumps(item["per100g"]) + ", \"image\": null },\n"

# Insert foods into foods.js
with codecs.open('frontend/js/data/foods.js', 'r', 'utf-8') as f:
    content = f.read()

# find the last ];
last_brace = content.rindex("];")
if last_brace != -1:
    new_content = content[:last_brace] + foods_str + content[last_brace:]
    with codecs.open('frontend/js/data/foods.js', 'w', 'utf-8') as f:
        f.write(new_content)

# Generate Prompts
prompts_str = "\\n"
for item in FOODS:
    filename = item['id'] + ".png"
    name = item['name'].split('(')[0].strip() # Clean name for prompt
    prompts_str += f"## {item['name']}\\n"
    prompts_str += f"- **Filename:** `{filename}`\\n"
    prompts_str += f"- **Prompt:** Professional food photography of {name}, authentic and accurate, gourmet plating on elegant crockery or appropriate packaging, top-quality restaurant presentation, vivid colors, dark moody background with dramatic lighting.\\n\\n"

with codecs.open('IMAGE_PROMPTS.md', 'a', 'utf-8') as f:
    f.write(prompts_str)

print("Insertion completed successfully.")
